config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'event#index'

  resources :event do
  	resources :attendances, except: [:new, :show, :edit] do
      resources :charges
      end
    end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :participate_send

  def participate_send
    AttendanceMailer.participate_email(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { greater_than: 0}
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  validate :is_future?
  validate :is_multiple_5?

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :orga, class_name: "User"

  def is_future?
    errors.add(:start_date, "La date de départ ne peut être passée") unless self.start_date.to_i > Time.now.to_i
  end

  def is_multiple_5?
    errors.add(:duration, "La durée (minutes) doit être multiple de 5") unless self.duration % 5 == 0
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email,  presence: true,  uniqueness: true,  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Format email incorrect" }
  validates :encrypted_password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :attendances
  has_many :events, through: :attendances
  has_many :organized_events, foreign_key: 'orga_id', class_name: "Event"

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

   def authenticate_user
     unless current_user
       flash[:danger] = "Connecte toi avant !"
       redirect_to new_user_session_path
     end
   end

  def new
    Attendance.new
  end

  def create
    @attendance = Attendance.new(event_id: params[:title], user_id: current_user.id)
    if @attendance.save
      flash[:success] = 'Votre participation est prise en compte'
      redirect_to root
    else
      flash[:alert] = 'Un problème est survenu, veuillez réessayer'
      render 'new'
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
end

def create
  # Amount in cents
  @amount = Event.find(params[:event_id]).price*100

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

Attendance.create(event_id: Event.find(params[:event_id]).id, user_id: current_user.id, stripe_customer_id: customer.id)

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

   def authenticate_user
     unless current_user
       flash[:danger] = "Connecte toi avant !"
       redirect_to new_user_session_path
     end
   end


  def index
    @images = ['https://blackwhite.pictures/public/uploads/thumbnail/blackwhite-photography-36271549213698klqcoxfiqq.jpeg', 'https://www.letelegramme.fr/images/2019/10/17/le-bunker-brestois-grand-messe-de-la-scene-electro-local_4862281_495x330p.jpg?v=1', 'http://studio-spaces.com/wp-content/uploads/2016/09/2_StudioSpaces_Events_Wedding_03.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTvz75lpxAuMhrm1NCV41VDDU00bIQ8N_rn8ky281kWcpoM2EgO', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRcuaAyWCW4biOA-C8BQ9e_Pi73X53nCkamqz4oYUf_5FaloHCg', 'https://apiumhub.com/wp-content/uploads/2017/01/become-a-software-developer.jpg']
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    Event.new
  end

    def create
          @images = ['https://blackwhite.pictures/public/uploads/thumbnail/blackwhite-photography-36271549213698klqcoxfiqq.jpeg', 'https://www.letelegramme.fr/images/2019/10/17/le-bunker-brestois-grand-messe-de-la-scene-electro-local_4862281_495x330p.jpg?v=1', 'http://studio-spaces.com/wp-content/uploads/2016/09/2_StudioSpaces_Events_Wedding_03.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTvz75lpxAuMhrm1NCV41VDDU00bIQ8N_rn8ky281kWcpoM2EgO', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRcuaAyWCW4biOA-C8BQ9e_Pi73X53nCkamqz4oYUf_5FaloHCg', 'https://apiumhub.com/wp-content/uploads/2017/01/become-a-software-developer.jpg']

      @event = Event.new(title: params[:title], description: params[:description], price: params[:price], start_date: params[:start_date], duration: params[:duration], location: params[:location], orga_id: current_user.id)
      if @event.save
        flash[:success] = 'Votre event a bien été créé'
        render 'index'
      else
        flash[:alert] = 'Votre event a bien été créé'
        render 'new'
      end
    end

    def edit
      
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]
  before_action:user_is_myself, only: [:show]

  def authenticate_user
    unless current_user
      flash[:danger] = 'Connecte toi avant !'
      redirect_to new_user_session_path
    end
  end

  def user_is_myself
    unless current_user == User.find(params[:id])
      redirect_to root_path
    end
  end

  def show
    @user=User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">
      <%= Event.find(:event_id).title %>
      <br>
      <span class="badge badge-primary">
        <%= @event.price %>€</span></h1>
    <p class="lead font-weight-normal"><%= @event.description %></p>

    <% if @event.users.include?(current_user) %>
      <p>Vous participez à cet évènement</p>

      <% elsif current_user && current_user.id != @event.orga_id || !current_user %>
        <%= link_to 'Participer', event_attendances_path(@event.id, current_user.id), class: 'btn btn-lg btn-primary' %>

        <% elsif current_user && current_user.id == @event.orga_id %>
          <%= link_to 'Modifier mon Event', edit_event_path, class: 'btn btn-lg btn-primary' %>

        <% end %>

      </div>
      <div class="product-device box-shadow d-none d-md-block"></div>
      <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">

      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden w-50">
        <div class="my-3 py-3">
          <h2 class="display-5">Quand ça ?</h2>
          <p class="lead"><%= @event.start_date.strftime('%a %b %d') %></p>
        </div>
        <div class="bg-light box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>

      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden w-50">
        <div class="my-3 p-3">
          <h2 class="display-5">Où ça ?</h2>
          <p class="lead"><%= @event.location %></p>
        </div>
        <div class="bg-dark box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>

    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">

      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden w-50">
        <div class="my-3 p-3">
          <h2 class="display-5">Qui sera là ?</h2>
          <p class="lead"><%= @event.users.count %>
            personnes participent à cet event.</p>
        </div>
        <div class="bg-dark box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>

      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden w-50">
        <div class="my-3 py-3">
          <h2 class="display-5">Organisé par:</h2>
          <p class="lead"><%= @event.orga.first_name%></p>
        </div>
        <div class="bg-light box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
      </div>

    </div>

app/views/attendances/new.html.erb
<h1>Test</h1>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<container class="d-flex align-items-center justify-content-center" style="height: 620px">
  <div class="row align-items-center">
    <div class="card m-5 p-1 " style="width: 400px;" >
      <div class="card-header bg-light text-center">
        <%= Event.find(params[:event_id]).title %>
      </div>
      <div class="card-body">
        <p> Pour participer à l'évènement, tu dois régler le montant demandé par l'organisateur</p>
        <%= form_tag event_attendance_charges_path(Event.find(params[:event_id]).id,current_user.id) do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <span>Montant: <%=Event.find(params[:event_id]).price%> euros</span>
            </label>
          </article>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="A month's subscription"
                data-amount=<%="#{Event.find(params[:event_id]).price*100}"%>
                data-locale="auto"></script>
        <% end %>
      </div>
    </div>
  </div>
</container>

app/views/event/index.html.erb
<header class="contain">
    <div class="p-5 title-banner">
      <h1 class="display-4">Trouve le prochain Event qui va changer ta vie !</h1>
      <p class="pt-3"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis ex cumque ab dolore, sit consequatur est! Quis aliquam a qui, nostrum, officia aut sed laudantium suscipit. Architecto recusandae reprehenderit, perferendis.</p>
      <div class="text-right pt-3">
      <%= link_to "Voir les Events", root_path, class: 'btn btn-outline-primary btn-lg mr-2' %>
      <%= link_to "Créer un Event", new_event_path, class: 'btn btn-primary btn-lg ' %>
      </div>
    </div>
</header>

<div class="container my-5 ml-5 pt-5">
  <h2 class="display-4 my-5 ml-5"><span class="list-title pb-1 px-3">Les prochains Events:</span</h2>
</div>

<div class="container py-5">
  <div class="row ">
    <% Event.all.each do |event| %>
    <div class="col-lg-4 p-3">
    <div class="card">
      <img class="card-img-top" src="<%= @images.sample %>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"> <%= event.title%> </h5>
        <h6 class="card-subtitle mb-2 py-1 text-muted"> <%= event.start_date.strftime('%a %b %d')%></h6>
        <p class="card-text card-limit"> <%= event.description[0..65] %>...</p>
        <a href="/event/<%=event.id%>" class="card-link btn btn-primary my-1">Découvrir</a> <span class="text-muted pl-5"><%= event.users.count%> personnes participent</span>
      </div>
    </div>
    </div>
    <% end %>

  </div>
</div>

app/views/event/new.html.erb
<% if @event !=nil%>
  <div class="alert alert-danger m-0 p-3 text-center" role="alert">
    <% @event.errors.each do |attr, msg|  %>
      <%= attr %>
      <%= msg %>
    <% end %>
  </div>
<% end %>

<div class="container">
    <div class="row mt-5">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5 px-4">
          <div class="card-body">
            <h5 class="card-title text-center"> <span class="list-title px-3 display-4">Créer un Event </span></h5>
            <%= form_tag url_for(action: 'create'), method: "post" do %>
            <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>

              <%= label_tag 'Le titre' %>
              <div class="form-label-group">
              <%= text_field_tag 'title', value = nil, placeholder: 'Quoi ?' %>
              </div>

              <%= label_tag "La description" %>
              <div class="form-label-group">
                <%= text_area_tag 'description', value = nil, placeholder: 'Décris ton event' %>
              </div>

              <%= label_tag 'La date' %>
              <div class="form-label-group">
                <%= date_field_tag 'start_date', value = nil, placeholder: 'Quand ?' %>
              </div>

              <%= label_tag 'Durée (en minutes)' %>
              <div class="form-label-group">
                <%= text_field_tag 'duration', value = nil, placeholder: 'Combien de temps' %>
              </div>

              <%= label_tag 'Le lieu' %>
              <div class="form-label-group">
              <%= text_field_tag 'location', value = nil, placeholder: 'Où cela se passe' %>
              </div>

              <%= label_tag 'Le prix' %>
              <div class="form-label-group">
              <%= text_field_tag 'price', value = nil, placeholder: 'Coût par participant' %>
              </div>

              <%= submit_tag "Créer l'Event", class: 'btn btn-lg btn-primary btn-block text-uppercase my-3' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/event/show.html.erb
<div class="position-relative overflow-hidden p-5 p-md-5 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">
      <%= @event.title %>
      <br>
      <span class="badge badge-primary">
        <%= @event.price %>€</span></h1>
        <p>Description :</p>
    <p class="lead font-weight-normal"><%= @event.description %></p>

    <% if @event.users.include?(current_user) %>
      <p>Vous participez à cet évènement</p>

      <% elsif current_user && current_user.id != @event.orga_id || !current_user %>
        <%= link_to 'Participer', new_event_attendance_charge_path(@event.id, current_user.id), class: 'btn btn-lg btn-primary' %>

        <% elsif current_user && current_user.id == @event.orga_id %>
          <%= link_to 'Modifier mon Event', edit_event_path, class: 'btn btn-lg btn-primary' %>

        <% end %>

      </div>

    </div>

    <div class="d-md-flex flex-md-equal my-md-3 pl-md-3 w-100">

      <div class="bg-dark py-5 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden col-md-6 blue-case">
        <div class="my-5 py-3">
          <h2 class="display-5 mt-5">Quand ça ?</h2>
          <p class="lead display-4 mb-5"><%= @event.start_date.strftime('%a %b %d') %></p>
        </div>
      </div>

      <div class="bg-light py-5 px-3 pt-md-5 px-md-5 text-center overflow-hidden col-md-6">
        <div class="my-5 p-3">
          <h2 class="display-5 mt-5">Où ça ?</h2>
          <p class="lead display-4 mb-5"><%= @event.location %></p>
        </div>
      </div>

    </div>

    <div class="d-md-flex flex-md-equal my-md-3 pl-md-3 w-100  ">

      <div class="bg-dark py-5 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden col-md-6 pic-case">
        <div class="my-5 p-3">
          <h2 class="display-5 mt-5">Qui sera là ?</h2>
          <p class="lead display-4 mb-5"><%= @event.users.count %> personnes participent à cet event.</p>
        </div>
      </div>

      <div class="bg-white py-5 px-3 pt-md-5 px-md-5 text-center overflow-hidden col-md-6">
        <div class="my-5 py-3">
          <h2 class="display-5 mt-5">Organisé par:</h2>
          <p class="lead display-4 mb-5"><%= @event.orga.first_name%></p>
        </div>
      </div>

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Carter+One&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top py-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
              EventbriteLike
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Accueil", root_path, class: 'nav-link text-uppercase mx-3 text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "Créer un Event", new_event_path, class: 'nav-link text-uppercase mx-3 text-white' %>
            </li>
            <% if user_signed_in? == false %>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle btn btn-outline-primary text-light mx-3 text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      S'inscrire / Se connecter
                    </a>
                    <!-- Here's the magic. Add the .animate and .slide-in classes to your .dropdown-menu and you're all set! -->
                    <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
                      <%= link_to "S'inscrire", new_user_registration_path, class: 'dropdown-item text-uppercase' %>
                      <div class="dropdown-divider"></div>
                      <%= link_to "Se Connecter", new_user_session_path, class: 'dropdown-item text-uppercase' %>
                    </div>
                  </li>
                </ul>
              </div>
            <% else %>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle btn btn-outline-primary text-light text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mon Profil
                  </a>
                  <!-- Here's the magic. Add the .animate and .slide-in classes to your .dropdown-menu and you're all set! -->
                  <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
                    <%= link_to "Mon Profil", user_path(current_user.id), class: 'dropdown-item text-uppercase' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Se Déconnecter", destroy_user_session_path, method: :delete, class: 'dropdown-item text-uppercase' %>
                  </div>
                </li>
              </ul>
            </div>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <footer class="container-fluid bg-dark text-center p-3">
       <p class="text-white">Made with Love, by Jordan Pedro</p>
    </footer>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
  <div class="row py-5">
    <h1 class="py-5"><span class="list-title px-3">Mon Profil</span></h1>
  </div>

    <div class="row py-3">
      Nom: <%= @user.last_name %>
    </div>

    <div class="row py-3">
      Prénom: <%= @user.first_name %>
    </div>

    <div class="row py-3">
      Email: <%= @user.email %>
    </div>

    <div class="row py-3">
      Description: <%= @user.description %>
    </div>
  </div>